cms/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace cms.Controllers
{
	public static class ExtensionMethods
	{
		public static bool HasValue(this Guid guid)
		{
			return guid != Guid.Empty;
		}

		public static string AddBackSlash(this string path)
		{
			return (!path.Trim().EndsWith(@"\")) ? path + @"\" : path;
		}

		public static DateTime? ToDateTime(this string s)
		{
			DateTime result;
			if (DateTime.TryParse(s, out result))
				return result;
			return null;
		}

		public static DateTime? ToDate(this string s)
		{
			DateTime result;
			if (DateTime.TryParse(s, out result))
				return result.Date;
			return null;
		}

		public static int? ToInt(this string s)
		{
			int result;
			if (int.TryParse(s, out result))
				return result;

			return null;
		}

		public static DateTime? NullOrDate(this DateTime? d)
		{
			if (d == null)
				return d;

			return (d.Value.Date);
		}

		private static System.Globalization.CultureInfo culture = new System.Globalization.CultureInfo("en-US");

		public static string ToReportParameter(this DateTime d)
		{
			return string.Format(culture, "{0:dd MMM yyyy}", d);
		}

		public static string ToReportParameter(this DateTime? d)
		{
			if (d == null || !d.HasValue)
				return string.Empty;

			return string.Format(culture, "{0:dd MMM yyyy}", d);
		}

		public static bool IsNumeric(this string value)
		{
			if (String.IsNullOrEmpty(value))
				return false;

			return !value.ToCharArray().Where(x => !Char.IsDigit(x)).Any();
		}


		public static DateTime MonthEnd(this DateTime date)
		{
			return new DateTime(date.Year, date.Month, DateTime.DaysInMonth(date.Year, date.Month));
		}

		public static DateTime FirstDayOfMonth(this DateTime date)
		{
			return new DateTime(date.Year, date.Month, 1);
		}


	}
}

cms/Controllers/usersController.cs
using DevExpress.Web.Mvc;
using cms;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Mail;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;
using cms.Models;
using MySql.Data.MySqlClient;

namespace cms.Controllers
{
	//   [Authorize]
	public class usersController : BaseController
    {
		// GET: users
		public ActionResult Index()
		{
			return View();
		}


		#region list users
	
		[HttpPost]

		private void SendEMail(string emailid, string subject, string body)
		{
			System.Net.Mail.SmtpClient client = new System.Net.Mail.SmtpClient();
			client.DeliveryMethod = System.Net.Mail.SmtpDeliveryMethod.Network;
			client.EnableSsl = true;
			client.Host = "smtp.gmail.com";
			client.Port = 587;


			System.Net.NetworkCredential credentials = new System.Net.NetworkCredential("prsappreply@gmail.com", "Mutheiwana27");
			client.UseDefaultCredentials = false;
			client.Credentials = credentials;

			System.Net.Mail.MailMessage msg = new System.Net.Mail.MailMessage();
			msg.From = new MailAddress("prsappreply@gmail.com");
			msg.To.Add(new MailAddress(emailid));

			msg.Subject = subject;
			msg.IsBodyHtml = true;
			msg.Body = body;

			client.Send(msg);
		}

		public ActionResult GridViewPartial()
		{
            var model = GetUser();
			return PartialView("_GridViewPartial", model.ToList());
		}


        #endregion

        #region userroles
        [ValidateInput(false)]
        public ActionResult UserRolesPartial(string UserId)
        {
            var model = GetUserRolesDto(UserId);
            return PartialView("_UserRoles", model.ToList());
        }


        private List<UserRolesDto> GetUserRolesDto(string userId)
        {
           
            List<UserRolesDto> roles = new List<UserRolesDto>();

            string constr = connectionString;
            using (MySqlConnection con = new MySqlConnection(constr))
            {
                string query = "SELECT rr.ObjId as UserRoleId, rl.Name as Rolename, ss.Id as userId,rl.Id as RoleId from UserRole rr JOIN User ss on rr.UserId = ss.Id JOIN Role rl on rr.RoleId = rl.Id  where ss.Id='" + userId + "'";

                using (MySqlCommand cmd = new MySqlCommand(query))
                {
                    cmd.Connection = con;
                    con.Open();
                    using (MySqlDataReader sdr = cmd.ExecuteReader())
                    {
                        while (sdr.Read())
                        {
                            roles.Add(new UserRolesDto
                            {
                                ObjId = Guid.Parse((sdr["UserRoleId"]).ToString()),
                                RoleName = sdr["Rolename"].ToString(),
                                // EmailConfirmed = bool.Parse(sdr["EmailConfirmed"].ToString()),
                                // Password = sdr["Password"].ToString(),
                                RoleId = sdr["RoleId"].ToString(),
                                // TempPassword = sdr["TempPassword"].ToString(),
                                UserId = sdr["userId"].ToString(),
                            });
                        }
                    }
                    con.Close();
                }
            }


            return roles.ToList();
        }


        private List<UserRolesDto> GetUserRolesNewDto()
        {

            List<UserRolesDto> roles = new List<UserRolesDto>();

            string constr = connectionString;
            using (MySqlConnection con = new MySqlConnection(constr))
            {
                string query = "SELECT rr.ObjId as UserRoleId, rl.Name as Rolename, ss.Id as userId,rl.Id as RoleId from UserRole rr JOIN User ss on rr.UserId = ss.Id JOIN Role rl on rr.RoleId = rl.Id";

                using (MySqlCommand cmd = new MySqlCommand(query))
                {
                    cmd.Connection = con;
                    con.Open();
                    using (MySqlDataReader sdr = cmd.ExecuteReader())
                    {
                        while (sdr.Read())
                        {
                            roles.Add(new UserRolesDto
                            {
                                ObjId = Guid.Parse((sdr["UserRoleId"]).ToString()),
                                RoleName = sdr["Rolename"].ToString(),
                                // EmailConfirmed = bool.Parse(sdr["EmailConfirmed"].ToString()),
                                // Password = sdr["Password"].ToString(),
                                RoleId = sdr["RoleId"].ToString(),
                                // TempPassword = sdr["TempPassword"].ToString(),
                                UserId = sdr["userId"].ToString(),
                            });
                        }
                    }
                    con.Close();
                }
            }


            return roles.ToList();
        }

        public ActionResult RolesPartial()
        {
            var mymodel = GetRole();
            return PartialView(mymodel);
        }

        //Function to get a list of roles 
        private List<RoleDto> GetRoles()
        {
            var mymodel = GetRole();
            return mymodel;
        }
        public ActionResult UserRolesEditHeaderFormPartial(string ObjId)
        {
            var userRoleModal = GetUserRolesDto(ObjId).Where(c => c.UserId.ToString() == ObjId).SingleOrDefault();

            //this will pass a list of roles to the front end
            ViewData["Roles"] = GetRoles();
            if (userRoleModal == null)
            {
                return PartialView("RolesEditPartialFormView", new UserRolesDto());
            }

            var model = GetUserRolesNewDto();

            return PartialView("RolesEditPartialFormView", model);

        }


        [HttpPost, ValidateInput(true)]
        public ActionResult UserRolesPartialAddNew(UserRolesDto item)
        {
            //var model = db.UserRoles;

            //if (ModelState.IsValid)
            //{
            //    try
            //    {
            //        // double check to ensure this new Id generated does not exist
            //        var userRole = db.UserRoles.Where(c => c.ObjId == item.ObjId).SingleOrDefault();

            //        // 1 get roleId, userid we want to insert
            //        // 2 query the userroles on the 2 values
            //        // only if we get nothing - .Any() is false, then can we insert.
            //        // if we find a record, return ViewData["EditError"] = "Role Already exists for User";

            //        var currentUserRoleToAddExists = db.UserRoles.Where(c => c.RoleId == item.RoleId && c.UserId == item.UserId).Any();

            //        if (userRole == null && currentUserRoleToAddExists == false)
            //        {
            //            var userR = new UserRole()
            //            {
            //                ObjId = item.ObjId,
            //                UserId = item.UserId,
            //                RoleId = item.RoleId
            //            }; ;

            //            userR.UserId = item.UserId;
            //            userR.RoleId = item.RoleId;
            //            model.Add(userR);
            //            db.SaveChanges();
            //        }
            //        else
            //        {
            //            if (currentUserRoleToAddExists == false)
            //                ViewData["EditError"] = "Role Already exists for User";
            //            else
            //                ViewData["EditError"] = "User Role Id Already Exist. This is not allowed on a New record. Please Contact Support.";
            //            //userRole.RoleId = item.RoleId;
            //            //model.Attach(userRole);
            //            //db.SaveChanges();
            //        }

            //    }
            //    catch (Exception e)
            //    {
            //        ViewData["EditError"] = e.Message;
            //    }
            //}
            //else
            //    ViewData["EditError"] = "Please, correct all errors.";
            //var modelReturn = GetUserRolesDto(item.UserId.ToString());
            //return PartialView("_UserRoles", modelReturn);

            return PartialView("_UserRoles");

        }

        [HttpPost, ValidateInput(true)]
        public ActionResult UserRolesGridViewPartialUpdate(UserRolesDto item)
        {
            //var model = db.UserRoles;
            //if (ModelState.IsValid)
            //{
            //    try
            //    {
            //        var userRole = db.UserRoles.Where(c => c.ObjId == item.ObjId).SingleOrDefault();

            //        if (userRole != null)
            //        {
            //            this.UpdateModel(userRole);
            //            db.SaveChanges();
            //        }

            //        else
            //        {
            //            userRole.RoleId = item.RoleId;
            //            model.Attach(userRole);
            //            db.SaveChanges();
            //            ;
            //        }
            //    }
            //    catch (Exception e)
            //    {
            //        ViewData["EditError"] = e.Message;
            //    }
            //}
            //else
            //    ViewData["EditError"] = "Please, correct all errors.";
            //var modelReturn = GetUserRolesDto(item.UserId.ToString());
            //return PartialView("_UserRoles", modelReturn);


            return PartialView("_UserRoles");
        }

        public ActionResult UserRolesGridViewPartialDelete(UserRolesDto item)
        {
            //var model = db.UserRoles;

            //if (item.ObjId != null)
            //{
            //    try
            //    {

cms/Views/users/Index.cshtml
@using (Html.BeginForm())
{
<script type="text/javascript">


    function OnUsersHeaderGridFocusedRowChanged(s, e) {

        //Get the User's Id from the selected row
        s.GetRowValues(s.GetFocusedRowIndex(), 'Id', OnGetRowValues);
    }

    function OnGetRowValues(values) {
        //return the selected value
        UsersGrid_ObjId = values;
        UserRoles_ObjId = values;

        UserRoles_GridView.PerformCallback();
    }
    function OnBeginCallback(s, e) {
        // alert('OnBeginCallback e:  ' + e);
        e.customArgs["UserId"] = UsersGrid_ObjId;

    }
    function InitialSetFocus(s, e) {
        if (s.GetFocusedRowIndex() < 0)
            s.SetFocusedRowIndex(0);
    }
    //User Roles
    function OnUsersHeaderHeaderGridFocusedRowChanged(s, e) {

        //Get the User's Id from the selected row
        s.GetRowValues(s.GetFocusedRowIndex(), 'Id', OnGetRowValues);
    }

    function OnUserRoleHeaderMenuItemClick(s, e) {

        if (e.item.name == "btnHeaderNew") {

            var index = UserRoles_GridView.GetFocusedRowIndex();

            //UserRoles_GridView is the name of the gridview
            UserRoles_GridView.AddNewRow(index);
            // call edit funtion from custom button
        }

        if (e.item.name == "btnHeaderEdit") {

            var index = UserRoles_GridView.GetFocusedRowIndex();
            //  alert('index : ' + index);
            UserRoles_GridView.StartEditRow(index);
            // call edit funtion from custom button
        }

        if (e.item.name == "btnHeaderDelete") {
            if (confirm("Confirm Delete?")) {
                var index = UserRoles_GridView.GetFocusedRowIndex();
                UserRoles_GridView.DeleteRow(index);
            }
        }
    }
   
  
    //Users Menu Buttons
    function OnUsersHeaderMenuItemClick(s, e) {
        //alert("I am here: So ya clicked he button over yonder then: " + e.item.name)
        //https://documentation.devexpress.com/#AspNet/DevExpressWebScriptsASPxClientGridView_UpdateEdittopic
        if (e.item.name == "btnHeaderNew") {

            var index = UsersGrid.GetFocusedRowIndex();

            UsersGrid.AddNewRow(index);
            // call edit funtion from custom button
        }

        if (e.item.name == "btnHeaderEdit") {

            var index = UsersGrid.GetFocusedRowIndex();
            //  alert('index : ' + index);

            UsersGrid.StartEditRow(index);
            // call edit funtion from custom button

        }

        // 1. get userId
        var userId = UsersGrid.GetRowKey(UsersGrid.GetFocusedRowIndex());
      

        if (userId == null || userId == "") {
            alert("No User Selected");
            return;
        }

        if (e.item.name == "btnHeaderReset") {
                  $.ajax({
                url: '@Url.Action("ForgotPassword", "users")',
                type: "POST",
                dataType: "text",
                traditional: true,
                data: { userId: userId },
                success: function (data) {
                    //UserCommodity_GridView.Refresh();
                    alert("Mail Sent");

                },
                error: function (xhr, textStatus, errorThrown) {
                    alert('Request Status: ' + xhr.status + '; Status Text: ' + textStatus + '; Error: ' + errorThrown);
                }
            });
        }

        if (e.item.name == "btnHeaderDelete") {
            if (confirm("Confirm Delete?")) {
                var index = UsersGrid.GetFocusedRowIndex();
                UsersGrid.DeleteRow(index);
            }
        }
        // 1. get userId
        var userId = UsersGrid.GetRowKey(UsersGrid.GetFocusedRowIndex());
        //   alert("UserId : " + userId);
        if (userId == null || userId == "") {
            alert("No User Selected");
            return;
        }

    }
</script>


@Html.Partial("UsersLandingFormView");

}

cms/Views/users/ResetPassword.cshtml
@{ Layout = "~/Views/Shared/_lightLayout.cshtml"; }

@model cms.Models.ResetPasswordViewModel
@{
    ViewBag.Title = "Reset password";
}

<div class="accountHeader">
    <h2>@ViewBag.Title</h2>
</div>
@using (Html.BeginForm("ResetPassword", "users", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <h4>Reset your password.</h4>
    @Html.HiddenFor(model => model.Code)

    @Html.DevExpress().TextBoxFor(m => m.Email, s =>
{
    s.Properties.Caption = "Email";
    s.Properties.CaptionSettings.Position = EditorCaptionPosition.Top;
    s.ShowModelErrors = true;
    s.Properties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.ImageWithText;
}).GetHtml()
    @Html.DevExpress().TextBoxFor(m => m.Password, s =>
{
    s.Properties.Caption = "Password";
    s.Properties.Password = true;
    s.Properties.CaptionSettings.Position = EditorCaptionPosition.Top;
    s.ShowModelErrors = true;
    s.Properties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.ImageWithText;
}).GetHtml()
    @Html.DevExpress().TextBoxFor(m => m.ConfirmPassword, s =>
{
    s.Properties.Caption = "Confirm Password";
    s.Properties.Password = true;
    s.Properties.CaptionSettings.Position = EditorCaptionPosition.Top;
    s.ShowModelErrors = true;
    s.Properties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.ImageWithText;
}).GetHtml()
    <br />
    @Html.DevExpress().Button(s =>
{
    s.Name = "Reset";
    s.Text = "Reset";
    s.UseSubmitBehavior = true;
}).GetHtml()
}

cms/Views/users/ResetPasswordConfirmation.cshtml
@{ Layout = "~/Views/Shared/_lightLayout.cshtml"; }

@{
    ViewBag.Title = "Reset password confirmation";
}
<div class="accountHeader">
    <h2>@ViewBag.Title</h2>
</div>
<p>
    Your password has been reset. Please @Html.ActionLink("click here to log in", "Login", "Account")
</p>

cms/Views/users/RolesEditPartialFormView.cshtml
@using DevExpress.Web;
@using DevExpress.Web.Mvc;
@using cms.Models;

@model cms.Models.UserRolesDto

@Html.HiddenFor(e => e.ObjId)
@*@Html.HiddenFor(e => e.RoleId)*@



@Html.DevExpress().FormLayout(settings =>
{
    // Get Fields
    settings.Name = "form1";

    var infoGroupItem = settings.Items.AddGroupItem(Gsettings =>
    {
        Gsettings.Caption = "User Roles Section";
        Gsettings.RowSpan = 4;
        Gsettings.ShowCaption = DefaultBoolean.True;
        Gsettings.ColCount = 1;
        Gsettings.Items.Add(e => e.RoleId,itemSettings =>
        {
            itemSettings.FieldName = "RoleDropDown";
            itemSettings.Caption = "";
            itemSettings.SetNestedContent(() =>
            {

                @Html.DevExpress().ComboBox(ComboBoxsettings =>
                {
                    Gsettings.Name = "Id";
                    ComboBoxsettings.Name = "RoleId";
                    ComboBoxsettings.Width = 500;
                    ComboBoxsettings.SelectedIndex = 1;
                    ComboBoxsettings.Properties.TextField = "Name";
                    ComboBoxsettings.Properties.ValueField = "Id";
                    ComboBoxsettings.Properties.DropDownStyle = DropDownStyle.DropDown;
                    ComboBoxsettings.ShowModelErrors = true;
            }).BindList(ViewData["Roles"]).Bind(Model.RoleName).Render();
        });
    });


    Gsettings.Items.Add(itemSettings =>
    {
        itemSettings.ShowCaption = DefaultBoolean.False;
        itemSettings.SetNestedContent(() =>
        {
            Html.ViewContext.Writer.Write("<div style='float:right'>");
            Html.DevExpress().Button(btnSettings =>
            {
                btnSettings.Name = "btnSave";
                btnSettings.Text = "Save";
                btnSettings.ClientSideEvents.Click = "function (s,e) {UserRoles_GridView.UpdateEdit();}";
            }).Render();

            Html.DevExpress().Button(btnSettings =>
            {
                btnSettings.Name = "btnCancel";
                btnSettings.Text = "Cancel";
                btnSettings.Style[HtmlTextWriterStyle.MarginLeft] = "5px";
                btnSettings.ClientSideEvents.Click = "function (s,e) {UserRoles_GridView.CancelEdit();}";
            }).Render();

            Html.ViewContext.Writer.Write("</div>");

        });

    });
});

}).GetHtml()

cms/Views/users/UserMenu.cshtml
@* User's Menu Header *@
<div style="padding-bottom: 10px; float: right;">
    @Html.DevExpress().Menu(settings =>
{
    settings.Name = "UsersMenu";
    settings.ShowAsToolbar = true;
    settings.ShowPopOutImages = DefaultBoolean.True;
    settings.Items.Add("New", "btnHeaderNew");
    settings.Items.Add("Reset Password", "btnHeaderReset");
    settings.Items.Add("Edit", "btnHeaderEdit");
    settings.Items.Add("Delete", "btnHeaderDelete");
    settings.Items.Add("Block User", "btnHeaderBlock");
    settings.Items.Add("UnBlock User", "btnHeaderUnBlock");
    settings.ClientSideEvents.ItemClick = "OnUsersHeaderMenuItemClick";
}).GetHtml()

cms/Views/users/UserRoleMenu.cshtml
@* User Role Menu Header *@
<div style="padding-bottom: 10px; float: right;">
    @Html.DevExpress().Menu(settings =>
{
    settings.Name = "UserRoleMenu";
    settings.ShowAsToolbar = true;
    settings.ShowPopOutImages = DefaultBoolean.True;
    settings.Items.Add("New", "btnHeaderNew");
    settings.Items.Add("Edit", "btnHeaderEdit");
    settings.Items.Add("Delete", "btnHeaderDelete");
    settings.ClientSideEvents.ItemClick = "OnUserRoleHeaderMenuItemClick";
}).GetHtml()
</div>

cms/Views/users/UsersChangePasswordForm.cshtml
@using DevExpress.Web;
@using DevExpress.Web.Mvc;
@using cms.Models;

@model cms.User


@using (Html.BeginForm()) {

    @Html.AntiForgeryToken()

    @Html.DevExpress().FormLayout(settings =>
{
    @Html.EnableClientValidation();

    bool isEdit = bool.Parse(ViewData["isEdit"].ToString() ?? "false");
    // Get Fields
    settings.Name = "ChangePasswordForm";
    settings.Width = Unit.Percentage(100);

    var infoGroupItem = settings.Items.AddGroupItem(Gsettings =>
    {
        Gsettings.Caption = "General";
        Gsettings.RowSpan = 4;
        Gsettings.ShowCaption = DefaultBoolean.False;
        Gsettings.ColCount = 1;
        Gsettings.SettingsItemHelpTexts.Position = HelpTextPosition.Bottom;

        if (isEdit == false)
        {
            Gsettings.Items.Add(TextFieldSettings =>
            {
                TextFieldSettings.ShowCaption = DefaultBoolean.True;
                TextFieldSettings.Caption = "Old Password";
                TextFieldSettings.SetNestedContent(() =>
                {
                    @Html.DevExpress().TextBox(
                        tb =>
                        {
                            //textboxsettings.Properties.Caption = "UserName        ";
                            tb.Name = "OldPassword";
                            tb.Properties.Password = true;
                            tb.Properties.CaptionSettings.Position = EditorCaptionPosition.Top;
                            tb.ShowModelErrors = true;
                            tb.Properties.ValidationSettings.Display = Display.Dynamic;
                            tb.Properties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.Text;
                            tb.Properties.ValidationSettings.ErrorTextPosition = ErrorTextPosition.Bottom;
                            tb.Properties.NullText = "Enter Old Password...";
                        }).Bind(Model.OldPassword).Render();
                });

            });
        }
        Gsettings.Items.Add(TextFieldSettings =>
        {
            TextFieldSettings.ShowCaption = DefaultBoolean.True;
            TextFieldSettings.Caption = "New Password";
            TextFieldSettings.SetNestedContent(() =>
            {
                @Html.DevExpress().TextBox(
               tb =>
               {
                   //textboxsettings.Properties.Caption = "NewPassword";
                   tb.Name = "NewPassword";
                   tb.Properties.Password = true;
                   tb.Properties.CaptionSettings.Position = EditorCaptionPosition.Top;
                   tb.ShowModelErrors = true;
                   tb.Properties.ValidationSettings.Display = Display.Dynamic;
                   tb.Properties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.Text;
                   tb.Properties.ValidationSettings.ErrorTextPosition = ErrorTextPosition.Bottom;
                   tb.Properties.NullText = "Enter New Password...";
               }).Bind(Model.NewPassword).Render();
            });

        });

        Gsettings.Items.Add(TextFieldSettings =>
        {
            TextFieldSettings.ShowCaption = DefaultBoolean.True;
            TextFieldSettings.Caption = "Confirm Password";
            TextFieldSettings.SetNestedContent(() =>
            {
                @Html.DevExpress().TextBox(
               tb =>
               {
                   //textboxsettings.Properties.Caption = "Email";
                   tb.Name = "Confirm Password";
                   tb.Properties.Password = true;
                   tb.Properties.CaptionSettings.Position = EditorCaptionPosition.Top;
                   tb.ShowModelErrors = true;
                   tb.Properties.ValidationSettings.Display = Display.Dynamic;
                   tb.Properties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.Text;
                   tb.Properties.ValidationSettings.ErrorTextPosition = ErrorTextPosition.Bottom;
                   tb.Properties.NullText = "Enter Confirm Password...";
               }).Bind(Model.ConfirmPassword).Render();
            });

        });
        // Buttons
        Gsettings.Items.Add(itemSettings =>
        {
            itemSettings.ShowCaption = DefaultBoolean.False;
            itemSettings.SetNestedContent(() =>
            {
                Html.ViewContext.Writer.Write("<div style='float:right'>");
                Html.DevExpress().Button(btnSettings =>
                {
                    btnSettings.Name = "btnSave";
                    btnSettings.Text = "Save";
                    btnSettings.RouteValues = new { Controller = "users", Action = "GridViewPartialUpdate" };
                    //btnSettings.UseSubmitBehavior = true;
                    //  btnSettings.ClientSideEvents.Click = "function (s,e) {UsersGrid.UpdateEdit();}";
                }).Render();

                Html.DevExpress().Button(btnSettings =>
                {
                    btnSettings.Name = "btnCancel";
                    btnSettings.Text = "Cancel";
                    btnSettings.Style[HtmlTextWriterStyle.MarginLeft] = "5px";
                    // btnSettings.ClientSideEvents.Click = "function (s,e) {UsersGrid.CancelEdit();}";
                }).Render();

                Html.ViewContext.Writer.Write("</div>");

            });

        });
    });
}).GetHtml()

  }

cms/Views/users/UsersLandingFormView.cshtml
@Html.DevExpress().FormLayout(settings =>
{
    settings.Name = "UsersLandingFormLayout";
    settings.AlignItemCaptionsInAllGroups = true;
    settings.Width = System.Web.UI.WebControls.Unit.Percentage(100);

    var groupMain = settings.Items.AddGroupItem(groupSettings =>
    {
        groupSettings.Caption = string.Format("Users");
        groupSettings.ShowCaption = DefaultBoolean.True;
        groupSettings.GroupBoxDecoration = GroupBoxDecoration.HeadingLine;
        groupSettings.SettingsItemCaptions.HorizontalAlign = FormLayoutHorizontalAlign.Left;
        groupSettings.ColCount = 1;
    });

    //Header Partial View of Users
    groupMain.Items.Add(itemSettings =>
    {
        itemSettings.Caption = "Users";
        itemSettings.Name = "Users";
        itemSettings.Width = System.Web.UI.WebControls.Unit.Percentage(100);
        itemSettings.ShowCaption = DefaultBoolean.False;
        itemSettings.ColSpan = 1;
        itemSettings.SetNestedContent(() =>
        {
            //return method
            @Html.RenderAction("GridViewPartial");
        });
    });

    groupMain.Items.Add(itemSettings =>
    {
        itemSettings.Width = System.Web.UI.WebControls.Unit.Percentage(100);
        itemSettings.ShowCaption = DefaultBoolean.False;
        itemSettings.ColSpan = 1;
        itemSettings.SetNestedContent(() =>
        {
            //return form
            @Html.RenderPartial("UserMenu");
        });
    });

    // Detail Partial View of UserRoles
    var UserRoleGroup = settings.Items.AddGroupItem(URSettings =>
    {
        URSettings.Caption = "User Roles";
        URSettings.RowSpan = 4;
        URSettings.ShowCaption = DefaultBoolean.True;
        URSettings.GroupBoxDecoration = GroupBoxDecoration.HeadingLine;
        URSettings.ColCount = 1;


        //load UserRoles
        URSettings.Items.Add(itemSettings =>
        {
            itemSettings.Width = System.Web.UI.WebControls.Unit.Percentage(100);
            itemSettings.ShowCaption = DefaultBoolean.False;
            itemSettings.ColSpan = 1;
            itemSettings.SetNestedContent(() =>
            {
                //return method
                @Html.RenderAction("UserRolesPartial");
            });
        });

        //URSettings.Items.Add(itemSettings =>
        //{
        //    itemSettings.Width = System.Web.UI.WebControls.Unit.Percentage(100);
        //    itemSettings.ShowCaption = DefaultBoolean.False;
        //    itemSettings.ColSpan = 1;
        //    itemSettings.SetNestedContent(() =>
        //    {
        //        //return form
        //        @Html.RenderPartial("UserRoleMenu");
        //    });
        //});

    });


}).GetHtml()