cms/Controllers/MainMenuController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using cms;
using cms.Models;
using MySql.Data.MySqlClient;
using System.Text;

namespace cms.Controllers
{
  //  [Authorize]
    public class MainMenuController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetEdit(string id)
        {
            ViewBag.CuizineType = id;
            return PartialView("CreateMainMenuEditPartial");

        }


        public ActionResult SavePayments(string PeopleId)
        {

            List<string> p = PeopleId.Split(',').ToList();
            try
            {
                string NoOfPeople = p[0];
                string Description = p[1];
                string emailId = p[2];
                string phoneNo = p[3];
                string CuisineType = p[4];
                string AddressId = p[5];
                //////////////////////////////////////////////////////////////
                string Duration = p[6];
                string TotalPriceId = p[7];
                string RequestDate = p[8];
                string NamesId = p[9];

                string fPhoneNo = phoneNo + ",";
                //////////////////////////////////////////////////////////////
                string RefNo = DateTime.Now.ToString("yyyy/MM/dd").Replace("/", "") + RandomString(4, false);

                ViewBag.RefNo = RefNo;
                insertrecords(NoOfPeople, emailId, fPhoneNo,  CuisineType, RefNo, AddressId, Duration, RequestDate, NamesId, Description, TotalPriceId);
                // SendEmail(emailId, RefNo, Occasionvalue, EventsType, CuisineType, TotalPriceId);
                SendSMS(NoOfPeople, emailId, fPhoneNo, CuisineType, RefNo, AddressId, Duration, RequestDate, NamesId, Description, TotalPriceId);

            }
            catch (Exception)
            {

                throw;
            }


            return PartialView("Payments");


        }

        // ubachefEntities db = new ubachefEntities();

        public void insertrecords(string PeopleId,  string emailId = "", string phoneNo = "",
           string CuisineType = "", string RefNo = "", string AddressId = "",
            string Duration = "", string RequestDate = "", string NamesId = "", string Description = "", string TotalPriceId = "")
        {

            try
            {
                //var model = db.bookings;

                booking Tosave = new booking();

                Tosave.ObjId = Guid.NewGuid();
                Tosave.people = PeopleId;
                Tosave.Description = Description;
                Tosave.email = emailId;
                Tosave.datecapture = DateTime.Now.ToString("yyyy/MM/dd");
                Tosave.Qualification = CuisineType;
                Tosave.phoneno = phoneNo;
                Tosave.refno = RefNo;
                Tosave.address = AddressId;
                Tosave.RequestDate = RequestDate;
                Tosave.Accepted = "No";
                Tosave.NamesId = NamesId;
                Tosave.Duration = Duration;
               
                //This is my insert query in which i am taking input from the user through windows forms  
                string Query = "insert into BookingTutor(ObjId,NoOfPeople,email,datecapture,Qualification,Description,phoneno,refno,address,Duration,RequestDate,Accepted,Names,TotalPrice) values('" +
                Tosave.ObjId + "','" + Tosave.people + "','" + Tosave.email + "','" + Tosave.datecapture 
                + "','" + Tosave.Qualification 
                + "','" + Description
                + "','" + Tosave.phoneno + "','" + Tosave.refno + "','" + Tosave.address
                + "','" + Tosave.Duration  + "','" + Tosave.RequestDate
                + "','" + Tosave.Accepted + "','" + Tosave.NamesId + "','" + TotalPriceId + "');";

                MySqlConnection MyConn2 = new MySqlConnection(connectionString);
                MySqlCommand MyCommand2 = new MySqlCommand(Query, MyConn2);
                MySqlDataReader MyReader2;
                MyConn2.Open();
                MyReader2 = MyCommand2.ExecuteReader();     // Here our query will be executed and data saved into the database.  

                MyConn2.Close();


            }
            catch (Exception)
            {

                throw;
            }


        }

        public void SendSMS(string PeopleId, string emailId = "", string phoneNo = "",
           string CuisineType = "", string RefNo = "", string AddressId = "",
            string Duration = "", string RequestDate = "", string NamesId = "", string Description = "", string TotalPriceId = "")
        {


            string to, msg;
            msg = "Dear " + NamesId + " You have Booked a Turtor for "  + "Duration of: " + Duration + " Minutes. "+"RefNo: " + RefNo + ". Amount to pay " + TotalPriceId;
            to = phoneNo;
            WebClient client = new WebClient();
            // Add a user agent header in case the requested URI contains a query.
            client.Headers.Add("user-agent", "Mozilla/4.0(compatible; MSIE 6.0; Windows NT 5.2; .NET CLR1.0.3705;)");
            client.QueryString.Add("user", "RomeoMulaudzi");
            client.QueryString.Add("password", "dAAdJKAHTfOJYc");
            client.QueryString.Add("api_id", "3546405");
            client.QueryString.Add("to", to);
            client.QueryString.Add("text", msg);
            string baseurl = "http://api.clickatell.com/http/sendmsg";
            Stream data = client.OpenRead(baseurl);
            StreamReader reader = new StreamReader(data);
            string s = reader.ReadToEnd();
            reader.Close();
            data.Close();

        }



        public static string ReplaceLastOccurrence(string Source, string Find, string Replace)
        {
            int Place = Source.LastIndexOf(Find);
            string result = Source.Remove(Place, Find.Length).Insert(Place, Replace);
            return result;
        }

        public string RandomString(int size, bool lowerCase)
        {
            StringBuilder builder = new StringBuilder();
            Random random = new Random();
            char ch;
            for (int i = 0; i < size; i++)
            {
                ch = Convert.ToChar(Convert.ToInt32(Math.Floor(26 * random.NextDouble() + 65)));
                builder.Append(ch);
            }
            if (lowerCase)
                return builder.ToString().ToLower();
            return builder.ToString();
        }
    }
}

cms/Views/MainMenu/CreateMainMenuEditPartial.cshtml
<!DOCTYPE html>

<meta http-equiv="content-type" content="text/html;charset=utf-8" /><!-- /Added by HTTrack -->
<html>


<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
    <title>SMART TUTOR</title>
    <link rel="apple-touch-icon" href="~/assets/images/apple-touch-icon.png" />
    <script>
        if (window.screen.height == 568) { // iPhone 4"
            document.querySelector("meta[name=viewport]").content = "width=320.1";
        }
    </script>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">

    <!-- css -->
    <link rel="stylesheet" href="~/Content/mobile/1.3.0/jquery.mobile-1.3.0.min.css" />
    <link rel="stylesheet" href="~/assets/css/style2.css">

    <!-- scripts -->
    <script src="~/Content/jquery-1.8.2.min.js"></script>
    <script src="~/Content/mobile/1.3.0/jquery.mobile-1.3.0.min.js"></script>
    <script src="~/assets/js/screen.js"></script>

</head>
<body>

    <div data-role="page">

        <!-- main content -->
        <div data-role="content" id="MyEditPageId">

            @if (ViewBag.CuizineType == "CERTIFICATE")
            {
                <!-- slider -->
                <div class="slider-outer">
                    <div class="slider-container">
                        <div id="camera_wrap">

                            <div data-src="assets/images/CLASSICBBQ/1.jpg" width="100%">
                                <div class="camera_caption fadeFromBottom">
                                </div>
                            </div>

                            <div data-src="assets/images/CLASSICBBQ/2.jpg" width="100%">
                                <div class="camera_caption fadeFromBottom" width="100%">
                                </div>
                            </div>

                            <div data-src="assets/images/CLASSICBBQ/3.jpg" width="100%">
                                <div class="camera_caption fadeFromBottom" width="100%">
                                </div>
                            </div>

                            <!--<div data-src="assets/images/headers/4.jpg">
                            </div>-->

                        </div>
                    </div>
                    <br class="clear" />
                </div>
                <!-- /slider -->
            }

            @if (ViewBag.CuizineType == "DIPLOMA")
            {
                <!-- slider -->
                <div class="slider-outer">
                    <div class="slider-container">
                        <div id="camera_wrap">

                            <div data-src="assets/images/PLATTERS/1.jpg" width="100%">
                                <div class="camera_caption fadeFromBottom">
                                </div>
                            </div>

                            <div data-src="assets/images/PLATTERS/2.jpg" width="100%">
                                <div class="camera_caption fadeFromBottom" width="100%">
                                </div>
                            </div>

                            <div data-src="assets/images/PLATTERS/3.jpg" width="100%">
                                <div class="camera_caption fadeFromBottom" width="100%">
                                </div>
                            </div>

                            <!--<div data-src="assets/images/headers/4.jpg">
                            </div>-->

                        </div>
                    </div>
                    <br class="clear" />
                </div>
                <!-- /slider -->
            }


            @if (ViewBag.CuizineType == "DEGREE")
            {
                <!-- slider -->
                <div class="slider-outer">
                    <div class="slider-container">
                        <div id="camera_wrap">

                            <div data-src="assets/images/ExecutiveSteak/1.jpg" width="100%">
                                <div class="camera_caption fadeFromBottom">
                                </div>
                            </div>

                            <div data-src="assets/images/ExecutiveSteak/2.jpg" width="100%">
                                <div class="camera_caption fadeFromBottom" width="100%">
                                </div>
                            </div>

                            <div data-src="assets/images/ExecutiveSteak/3.jpg" width="100%">
                                <div class="camera_caption fadeFromBottom" width="100%">
                                </div>
                            </div>

                            <!--<div data-src="assets/images/headers/4.jpg">
                            </div>-->

                        </div>
                    </div>
                    <br class="clear" />
                </div>
                <!-- /slider -->
            }


            <section>
                <h2>Provide the following</h2>

                <input type="hidden" id="CuizineTypeId" name="CuizineTypeId" value="@ViewBag.CuizineType" />

                <p>
                    <label for="People">
                        <span>No Of People:</span>
                        <strong><abbr title="required">*</abbr></strong>
                    </label>
                    <input type="number" id="People" name="People">
                </p>

                <p>
                    <label for="RequestDate ">
                        <span>Request Date: (2 days in advance)</span>
                        <strong><abbr title="required">*</abbr></strong>
                    </label>
                    <input type="date" id="RequestDate" name="RequestDate">
                </p>

                <p>
                    <label for="Duration">
                        <span>Duration: (Min 45 Minutes)</span>
                        <strong><abbr title="required">*</abbr></strong>
                    </label>
                    <input type="number" id="Duration" onchange="OnDuration()" name="Duration">
                </p>

                <p>
                    <label for="Description">
                        <span>Topic(Description):</span>

                    </label>
                    <input type="text" id="Description" name="Description">
                </p>

                <p>
                    <label for="AddressId">
                        <span>Place of Turtor:</span>

                    </label>
                    <input type="text" id="AddressId" name="AddressId">
                </p>

                <p>
                    <label for="Names">
                        <span>Name and Surname:</span>

                    </label>
                    <input type="text" id="Names" name="Names">
                </p>

                <p>
                    <label for="emailId">
                        <span>Email:</span>
                        <strong><abbr title="required">*</abbr></strong>
                    </label>
                    <input type="email" id="emailId" name="emailId">
                </p>

                <p>
                    <label for="phoneNo">
                        <span>Phone No:(start with country code e.g +27)</span>
                        <strong><abbr title="required">*</abbr></strong>
                    </label>
                    <input type="tel" id="phoneNo" name="phoneNo">
                </p>

                <label for="pricevalueId">
                    <span>Total Price:</span>
                </label>
                <input type="text" id="pricevalueId" name="pricevalueId" style="text-align:center; background-color: red;  color: white;" value="" disabled>

                <p id="TotalPriceId"></p>

                <p>
                    <input type="button" id="Request" onclick="myFunction()" value="Request Tutor" name="Request">
                </p>
            </section>

        </div>
        <!-- /content -->

    </div><!-- /page -->
    <!-- slider -->
    <script>
        jQuery(function () {
            jQuery('#camera_wrap').camera({

            });
        });
    </script>
    <!-- /slider -->

    <script>

        function showHide() {
            //create an object reference to the div containing images 
            var oimageDiv = document.getElementById('searchingimageDiv')
            //set display to inline if currently none, otherwise to none 
            oimageDiv.style.display = (oimageDiv.style.display == 'none') ? 'inline' : 'none'
        } 


        function myFunction() {

            var PeopleId = document.getElementById("People").value;
            var NamesId = document.getElementById("Names").value;
            var Duration = document.getElementById("Duration").value;
            var emailId = document.getElementById("emailId").value;
            var phoneNo = document.getElementById("phoneNo").value;
            var AddressId = document.getElementById("AddressId").value;
            var TotalPriceId = document.getElementById("pricevalueId").value;
            var CuizineTypeId = document.getElementById("CuizineTypeId").value;
            var Description = document.getElementById("Description").value;
            var RequestDate = document.getElementById("RequestDate").value;

            var MyIdInfo = PeopleId + "," + Description + "," + emailId + "," + phoneNo
                + "," + CuizineTypeId + "," + AddressId + "," + Duration  + "," + TotalPriceId + "," + RequestDate + "," + NamesId + "";

            if (PeopleId == "") {

                alert("Please enter no of people");
                return;
            }

            if (phoneNo == "") {

                alert("Please enter phone no.");
                return;
            }

            if (RequestDate == "") {

                alert("Please enter Request Date");
                return;
            }

            if (TotalPriceId == "") {

                alert("No Price Captured");
                return;
            }

            if (TotalPriceId < 0) {

                alert("Price Cannot be less than 0");
                return;
            }
            
            document.getElementById('MyEditPageId').style.display = 'none';
  
            window.location.href = "/MainMenu/SavePayments?PeopleId=" + MyIdInfo;

        }

        function OnDuration() {
            var PeopleId = document.getElementById("Duration").value;
            var CuizineTypeId = document.getElementById("CuizineTypeId").value;


            var results = parseInt(document.getElementById("Duration").value);


            if (CuizineTypeId == "CERTIFICATE")
            {
                if (results > 0) {
                    var answer = PeopleId / 0.45;
                    parseFloat(answer).toFixed(2);
                    document.getElementById("pricevalueId").value = "R" + parseFloat(answer).toFixed(2);;

                }

            }

            if (CuizineTypeId == "DIPLOMA") {
                if (results > 0) {
                    //document.getElementById("pricevalueId").value = "R300.00";

                    var answer = PeopleId / 0.50;

                    document.getElementById("pricevalueId").value = "R" + parseFloat(answer).toFixed(2);;

                }

            }

            if (CuizineTypeId == "DEGREE") {
                if (results > 0) {

                   // document.getElementById("pricevalueId").value = "R300.00";

                    var answer = PeopleId / 0.60;

                    document.getElementById("pricevalueId").value = "R" + parseFloat(answer).toFixed(2);;

                }


            }

                 }


    </script>

</body>
</html>

cms/Views/MainMenu/Index.cshtml
@{ Layout = null; }

@inherits System.Web.Mvc.WebViewPage

<!DOCTYPE html>

<meta http-equiv="content-type" content="text/html;charset=utf-8" /><!-- /Added by HTTrack -->

<html>

<head>

    <style>

.navbar {
  overflow: hidden;
  background-color: #333;
  position: fixed;
  bottom: 0;
  width: 100%;
}

.navbar a {
  float: left;
  display: block;
  color: #ff006e;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

.navbar a:hover {
  background-color: #ddd;
  color: black;
}

.navbar a.active {
  background-color: #4CAF50;
  color: white;
}

.navbar .icon {
  display: none;
}
    </style>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
    <title>SMART TUTOR</title>
    <link rel="apple-touch-icon" href="~/assets/images/apple-touch-icon.png" />
    <script>
        if (window.screen.height == 568) { // iPhone 4"
            document.querySelector("meta[name=viewport]").content = "width=320.1";
        }
    </script>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">

    <!-- css -->
    <link rel="stylesheet" href="~/Content/mobile/1.3.0/jquery.mobile-1.3.0.min.css" />
    <link rel="stylesheet" href="~/assets/css/style2.css">

    <!-- scripts -->
    <script src="~/Content/jquery-1.8.2.min.js"></script>
    <script src="~/Content/mobile/1.3.0/jquery.mobile-1.3.0.min.js"></script>
    <script src="~/assets/js/screen.js"></script>

</head>


<div id="home-page" data-role="page">

    <!-- slider -->
    <script>
        jQuery(function () {
            jQuery('#camera_wrap').camera({

            });
        });
    </script>
    <!-- /slider -->
    <!-- header -->
    @*<div data-role="header" class="page-header">
        <div class="logo"></div>
    </div>*@
    <!--/header -->
    <!-- main content -->
    <div data-role="content">

        <!-- slider -->
        <div class="slider-outer">
            <div class="slider-container">
                <div id="camera_wrap">

                    <div data-src="assets/images/SlideShow/1.jpg" width="100%">
                        <div class="camera_caption fadeFromBottom">
                        </div>
                    </div>

                    <div data-src="assets/images/SlideShow/2.jpg" width="100%">
                        <div class="camera_caption fadeFromBottom" width="100%">
                        </div>
                    </div>

                    <div data-src="~/assets/images/SlideShow/3.jpg" width="100%">
                        <div class="camera_caption fadeFromBottom" width="100%">
                        </div>
                    </div>

                    <div data-src="~/assets/images/SlideShow/4.jpg" width="100%">
                        <div class="camera_caption fadeFromBottom">
                        </div>
                    </div>

                    @*<div data-src="~/assets/images/SlideShow/5.jpg" width="100%">
                        <div class="camera_caption fadeFromBottom">
                        </div>
                    </div>

                    <div data-src="~/assets/images/SlideShow/6.jpg" width="100%">
                        <div class="camera_caption fadeFromBottom">
                        </div>
                    </div>

                    <div data-src="~/assets/images/SlideShow/7.jpg" width="100%">
                        <div class="camera_caption fadeFromBottom">
                        </div>
                    </div>

                    <div data-src="~/assets/images/SlideShow/8.jpg" width="100%">
                        <div class="camera_caption fadeFromBottom">
                        </div>
                    </div>

                    <div data-src="~/assets/images/SlideShow/9.jpg" width="100%">
                        <div class="camera_caption fadeFromBottom">
                        </div>
                    </div>*@
                    <!--<div data-src="assets/images/headers/4.jpg">
                    </div>-->

                </div>
            </div>
            <br class="clear" />
        </div>
        <!-- /slider -->

        <div class="shadow1box">
            <img src="assets/images/shadow1.png" class="shadow1" alt="shadow">
        </div>

        <div class="content-padd">

            <hr class="ornamental" />
            <h3 class="home-title">REQUEST PRIVATE TUTOR</h3>

            <hr class="ornamental" />

            <!-- navigation -->
            <ul data-role="listview" data-inset="true" id="listview" style="margin-bottom:0px">
                <li><a onclick="myFunction1()" data-transition="flip" data-prefetch>CERTIFICATE</a></li>
                <li><a onclick="myFunction2()" data-transition="flip" data-prefetch>DIPLOMA</a></li>
                <li><a onclick="myFunction3()" data-transition="flip" data-prefetch>DEGREE</a></li>
            </ul>

            <div class="navbar">
                <a onclick="myFunction4()" class="active">Turtors</a>
                @*<a onclick="myFunction5()">SUPPLIERS</a>
                <a href="">Contact</a>*@
            </div>
    </div>
    <script>
        function openNav() {
            document.getElementById("mySidenav").style.width = "250px";
        }

        function closeNav() {
            document.getElementById("mySidenav").style.width = "0";
        }
        function myFunction1() {


            window.location.href = "/MainMenu/GetEdit?Id=" + "CERTIFICATE";

        }

        function myFunction2() {


            window.location.href = "/MainMenu/GetEdit?Id=" + "DIPLOMA";

        }

        function myFunction3() {


            window.location.href = "/MainMenu/GetEdit?Id=" + "DEGREE";

        }

        function myFunction4() {


            window.location.href = "/ChefMobileRegister/Index";

        }

        //function myFunction5() {


        //    window.location.href = "/SupplierMobileRegister/Index";

        //}
    </script>
</div>

cms/Views/MainMenu/Payments.cshtml
<!DOCTYPE html>

<meta http-equiv="content-type" content="text/html;charset=utf-8" /><!-- /Added by HTTrack -->
<html>


<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
    <title>Payment Methods</title>
    <link rel="apple-touch-icon" href="~/assets/images/apple-touch-icon.png" />
    <script>
        if (window.screen.height == 568) { // iPhone 4"
            document.querySelector("meta[name=viewport]").content = "width=320.1";
        }
    </script>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">

    <!-- css -->
    <link rel="stylesheet" href="~/Content/mobile/1.3.0/jquery.mobile-1.3.0.min.css" />
    <link rel="stylesheet" href="~/assets/css/style2.css">

    <!-- scripts -->
    <script src="~/Content/jquery-1.8.2.min.js"></script>
    <script src="~/Content/mobile/1.3.0/jquery.mobile-1.3.0.min.js"></script>
    <script src="~/assets/js/screen.js"></script>

</head>
<body>

    <div data-role="page">

        <!-- header -->
        @*<div data-role="header" class="page-header">
                <a href="index.html" data-icon="arrow-l" data-iconpos="notext" data-direction="reverse" data-rel="back">Back</a>
                <div class="logo"></div>
                <a href="index.html" data-icon="home" data-iconpos="notext" rel="external" class="ui-btn-right">Home</a>
            </div>*@
        <!--/header -->
        <!-- main content -->
        <div data-role="content">


            <!-- slider -->
            <div class="slider-outer">
                <div class="slider-container">
                    <div id="camera_wrap">

                        <div data-src="assets/images/PaymentMethods/1.png" width="100%">
                            <div class="camera_caption fadeFromBottom">
                            </div>
                        </div>

                        <div data-src="assets/images/PaymentMethods/2.jpg" width="100%">
                            <div class="camera_caption fadeFromBottom" width="100%">
                            </div>
                        </div>

                        <div data-src="assets/images/PaymentMethods/3.png" width="100%">
                            <div class="camera_caption fadeFromBottom" width="100%">
                            </div>
                        </div>

                        <!--<div data-src="assets/images/headers/4.jpg">
                        </div>-->

                    </div>
                </div>
                <br class="clear" />
            </div><!-- /slider -->
            <section style="text-align:center">
                <h2>Booking information</h2>

                <h3>Booking Completed</h3>

                <h3>Booking RefNo : @ViewBag.RefNo</h3>

                <h4> Banking Details will be sent via Email and through SMS</h4>

                <h4> Please send proof of payment here: payments@smartutor.co.za</h4>

                <h4> For Enquiries: Enquiry@smartutor.co.za</h4>

            </section>

        </div><!-- /content -->

    </div><!-- /page -->
    <!-- slider -->
    <script>
        jQuery(function () {
            jQuery('#camera_wrap').camera({

            });
        });
    </script>
    <!-- /slider -->

    <script>
        function myFunction() {

            //var PeopleId       = document.getElementById("People").value;
            //var numberofplates = document.getElementById("numberofplates").value;
            //var emailId = document.getElementById("emailId").value;
            //var phoneNo = document.getElementById("phoneNo").value;

            //var e = document.getElementById("EventId");
            //var EventIdValue = e.options[e.selectedIndex].value;
            ////alert(e); //ID002


            //var ee = document.getElementById("OccasionId");
            //var OccasionIdValue = ee.options[ee.selectedIndex].value;
           // alert(ee); //ID002

                @*$.ajax({
                url: '@Url.Action("SavePayments", "MainMenu")',
                type: "POST",
                //dataType: "json", // if we speficy this we must return json from the controller method. this way we dont need to return anything
                dataType: "text",
                traditional: true,
                async: false,
                    data: { PeopleId: PeopleId, numberofplates: numberofplates, emailId: emailId, phoneNo: phoneNo, Occasionvalue: OccasionIdValue, EventsType: EventIdValue, CuisineType: "Classic BBQ"  },
                success: function (data) {
                },
                error: function (xhr, textStatus, errorThrown) {
                    alert('Request Status: ' + xhr.status + '; Status Text: ' + textStatus + '; Error: ' + errorThrown);

                }
            });*@
        }
    </script>

</body>
</html>